name: Daily Weather Automation

on:
#  schedule:
#    - cron: '0 3 * * *'  # Runs every day at 03:00 UTC (~8:30 AM IST)
  workflow_dispatch:

jobs:
  run-weather-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Run Main Script
        env:
          API_KEY: ${{ secrets.WEATHER_API_KEY }}
          HEADLESS: "true"
        run: python main.py
